---
version: 3
services:
  db:
    restart: always
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mybase
      MYSQL_USER: lvv
      MYSQL_PASSWORD: lvv_pass

  app:
    restart: always
    container_name: app
    image: myapp:latest
    depends_on:
      - db
    
    

  nginx:
    restart: always
    container_name: nginx
    image: nginx
