apiVersion: v1
kind: Namespace
metadata:
  name: app-js
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      namespace: app-js
      labels:
        app: app
    spec:
      containers:
        - name: app-js
          image: __VERSION__
          imagePullPolicy: Always