apiVersion: v1
kind: Service
metadata:
  name: web-nginx-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx-deployment
spec:
  selector:
    matchLabels:
      app: web-nginx
  replicas: 10
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: web-nginx
          image: nginx:stable
          ports:
            - containerPort: 80