apiVersion: v1
kind: Service
metadata:
  name: web-nginx-public
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: plaintext
    targetPort: 80
  # Kubernetes-метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: web-nginx