kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume  # Задается имя PV
  labels:
    type: local  # Тип PV задается local
    app: mysql-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Задается том PV
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim  # Задается имя PVC
  labels:
    app: mysql-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Задается доступ для чтения и записи
  resources:
    requests:
      storage: 5Gi  # Задается размер тома